In [1]:
import numpy as np
np.set_printoptions(suppress = True,
                   linewidth = 100,
                   precision = 2)
#suppress is used so that there are no scientific notations
#linewidth to show number of characters
#precision to see the decimal points

In [2]:
#now I should import the data by using loadtxt ot genfromtxt
raw_data = np.genfromtxt("loan-data.csv", 
                         delimiter=';',
                        skip_header = 1, #since it is all nan
                        autostrip=True) #to eleminate all white sppaces
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [3]:
#now I should uses isna to see the missing values
np.isnan(raw_data).sum()

88005

In [7]:
temporary_fill = np.nanmax(raw_data) + 1
temporary_mean = np.nanmean(raw_data, axis = 0)
#the below warning simply means that there are columns which have NaN data

C:\Users\DELL\AppData\Local\Temp\ipykernel_2436\2714538650.py:2: RuntimeWarning: Mean of empty slice
  temporary_mean = np.nanmean(raw_data, axis = 0)


In [8]:
temporary_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [12]:
temporary_stats = np.array([np.nanmin(raw_data, axis = 0),
                           temporary_mean,
                           np.nanmax(raw_data, axis = 0)])

C:\Users\DELL\AppData\Local\Temp\ipykernel_2436\2361176877.py:1: RuntimeWarning: All-NaN slice encountered
  temporary_stats = np.array([np.nanmin(raw_data, axis = 0),
C:\Users\DELL\AppData\Local\Temp\ipykernel_2436\2361176877.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data, axis = 0)])


In [13]:
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])