# 1st Data Analyst Project

#### S1: Eye ball the data see it in a text editor or excel
#### S2: Find as much information from it as possible

###### I1.) We have a .csv file
   
###### I2.) The separator is ';'

###### I3.) Data is a combination of Strings and Numbers

###### I4.) There are roughly 14 cols and 10000 rows
   
###### I5.) File contains web urls
   
###### I6.) The possibility of NaN and missing data is considerable 

###### I7.) The data is of year 2015
###### genfromtxt must be prefered over loadtxt</b>

In [1]:
#Import NumPy
import numpy as np

In [2]:
#setting print options
np.set_printoptions(suppress = True,
                   linewidth = 100,
                   precision = 2)

In [3]:
raw_data = np.genfromtxt("loan-data.csv",
                     delimiter=';',
                     skip_header= 1,
                     autostrip = True)

In [4]:
raw_data

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

In [5]:
#let's find missing values
np.isnan(raw_data).sum()

88005

In [6]:
temp_fill = np.nanmax(raw_data) + 1 #create the filler value
temp_mean = np.nanmean(raw_data, axis = 0) #create an array of mean

C:\Users\DELL\AppData\Local\Temp\ipykernel_8712\128708969.py:2: RuntimeWarning: Mean of empty slice
  temp_mean = np.nanmean(raw_data, axis = 0) #create an array of mean


In [7]:
temp_mean

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [8]:
temp_stats = np.array([np.nanmin(raw_data, axis = 0),
                      temp_mean,
                      np.nanmax(raw_data, axis = 0)])
#basic stats of the data

C:\Users\DELL\AppData\Local\Temp\ipykernel_8712\2110386613.py:1: RuntimeWarning: All-NaN slice encountered
  temp_stats = np.array([np.nanmin(raw_data, axis = 0),
C:\Users\DELL\AppData\Local\Temp\ipykernel_8712\2110386613.py:3: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data, axis = 0)])


In [9]:
temp_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [10]:
#So as we already know the data has text data and numeric data
# we will split it accordingly
column_string = np.argwhere(np.isnan(temp_mean)).squeeze()
#In this code the temp_mean is the input
#with np.isnan we will know weather the value is NaN
#np.argwhere will tell the index of the satisfied condition
#.squeeze() is used to print all the indices in the same line

In [11]:
column_string

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [12]:
column_numeric = np.argwhere(np.isnan(temp_mean) == False).squeeze()
column_numeric
#In this code the temp_mean is the input
#with np.isnan == False we will know weather the value is not NaN
#np.argwhere will tell the index of the satisfied condition
#.squeeze() is used to print all the indices in the same line

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

In [13]:
#Reimporting data set but only with strings
loan_data_strings = np.genfromtxt('loan-data.csv',
                                 delimiter = ';',
                                 skip_header= 1,
                                 autostrip = True,
                                 usecols = column_string,
                                 dtype = np.str_)
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [14]:
#Reimporting data set but only with numbers
loan_data_numeric = np.genfromtxt('loan-data.csv',
                                 delimiter = ';',
                                 skip_header= 1,
                                 autostrip = True,
                                 usecols = column_numeric,
                                 filling_values = temp_fill) #use to fill the missing values with the temporary_fill
loan_data_numeric

#NOTE: currently temp_fill is the largest number of the dataso it's easy to find

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [15]:
#Before we start digging deeper in the data set we need to give names to columns
#Since in the beginning we skipped headers

#Reimporting data set but only with strings
header_full = np.genfromtxt('loan-data.csv',
                                 delimiter = ';',
                                 autostrip = True,
                                 skip_footer= raw_data.shape[0], #skipps all the rows
                                 dtype = np.str_)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [16]:
header_strings, header_numeric = header_full[column_string], header_full[column_numeric]
#As we have given input as column_sting and column_numeric
#We have tolf to program to designate the respective column names to the data which it belongs to

In [17]:
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [18]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

#### Before we start preprocessing and manipulating data lets make checkpoints which is useful to avoid data loss

In [19]:
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, 
             header = checkpoint_header, 
             data = checkpoint_data)
    checkpoint_variable = np.load(file_name + ".npz")
    return(checkpoint_variable)

#we created a checkpoint which is a .npz file
#here the data is stored in different compartment but in same file
#Just like a excel workbook
#So here we first give file name
#then we store header in one array and data in the next one
#then we store this into a variable and return it by loading it

In [20]:
checkpoint_test = checkpoint("checkpoint-test",
                            header_strings,
                            loan_data_strings)

In [21]:
checkpoint_test["data"]

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [22]:
np.array_equal(checkpoint_test["data"], loan_data_strings)
#if in place of .array_equal we use just .equal
#it will individually check each element

True

### Manipulating String Columns

In [23]:
header_strings

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [24]:
#as we knwo it is necessary to give meaningfull names to columns
header_strings[0] = "issue_date"

In [25]:
loan_data_strings
#Let's examine this more deeply

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

###### Issue_date

In [26]:
#as we can see the 1st column in the above code contains month and year lets seperate it
loan_data_strings[:,0]
#-15 repeats a lot 
#So the data is of 2015

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [27]:
#let's see the unique values
np.unique(loan_data_strings[:,0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [28]:
#let's remove -15 as it is repeated
#and we know the tear of data
loan_data_strings[:,0] = np.chararray.strip(loan_data_strings[:,0], '-15')

In [29]:
np.unique(loan_data_strings[:,0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [30]:
#as strings take more space lets store all the months in numbers
#this helps us to store data is less space
month = np.array(['','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'])

In [31]:
for i in range(13):
    loan_data_strings[:,0] = np.where(loan_data_strings[:,0] == month[i],
                                     i,
                                     loan_data_strings[:,0])

In [32]:
np.unique(loan_data_strings[:,0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

###### Loan Status

In [33]:
header_strings #It just tells us the name of various headers

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [34]:
np.unique(loan_data_strings[:,1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [35]:
np.unique(loan_data_strings[:,1]).size

9

<b>Here we can use np.where() to assign a different number to each one but as we know regression only care if the candidate is in a stable financial condition or not, so we need to make this in a 0,1 situation</b> So we use the "unique" values and catagorise them in good and bad 

In [36]:
status_bad = np.array(['','Charged Off','Default','Late (31-120 dats)'])
#the bad category

In [37]:
loan_data_strings[:,1] = np.where(np.isin(loan_data_strings[:,1], status_bad),
                                 0,
                                 1)

In [38]:
np.unique(loan_data_strings[:, 1])

array(['0', '1'], dtype='<U69')

###### Term

In [39]:
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [40]:
loan_data_strings[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [41]:
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [42]:
#since month is repeated we should strip it
loan_data_strings[:,2] = np.chararray.strip(loan_data_strings[:,2], ' months')

In [43]:
np.unique(loan_data_strings[:,2])

array(['', '36', '60'], dtype='<U69')

In [44]:
#let's give this column meaning full name
header_strings[2] = "term_months"

In [45]:
#since we know there are missing values we assume the worst for them
loan_data_strings[:,2] = np.where(loan_data_strings[:,2] == '',
                                 '60',
                                 loan_data_strings[:,2])
loan_data_strings[:,2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [46]:
np.unique(loan_data_strings[:,2])

array(['36', '60'], dtype='<U69')

### Grade and Subgrade

In [47]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [48]:
loan_data_strings[:,3]

array(['C', 'A', 'B', ..., 'A', 'D', 'A'], dtype='<U69')

In [49]:
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [50]:
loan_data_strings[:,4]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [51]:
np.unique(loan_data_strings[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

Now if we see both the above outputs, we understand that the 2nd one is way better in grading data then the first and what ever data we can get from grade can be obtained by using sub-grade. So we can assume that it is a case of redone. BUT, we can use the grade to deal with missing values in a much effective way.

In [52]:
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where((loan_data_strings[:,4] == '') & (loan_data_strings[:,3] == i),
                                     i + '5',
                                     loan_data_strings[:,4])
#the given loop takes comparison values from grade and compairs it with sub-grade. 
#np.where 1st checks if the value is empty and then if the grade is the same as what we are taking as an input
#if it's true we put 5 after the grade or else we don't change it at all.

In [53]:
np.unique(loan_data_strings[:,4], return_counts=True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [54]:
#there a over 10000 values in this data base so if just 9 are missing we can drop it
# but as good data analyst we will make sure that we have made sure that atleast we can identify them
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4] = np.where(loan_data_strings[:,4] == '',
                                     'H1',
                                     loan_data_strings[:,4])


In [55]:
np.unique(loan_data_strings[:,4], return_counts=True)

(array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
        'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
        'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69'),
 array([285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250,
        255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5,   9],
       dtype=int64))

### Removing Grade
We will now remove the grade column cause it is not needed

In [56]:
loan_data_strings = np.delete(loan_data_strings,3,axis = 1)

In [57]:
loan_data_strings[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [58]:
header_strings = np.delete(header_strings,3)

In [59]:
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

### Converting Sub Grade
Now we should convert sub-grades to numbers

In [60]:
np.unique(loan_data_strings[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [61]:
keys = list(np.unique(loan_data_strings[:,3]))
value = list(range(1, np.unique(loan_data_strings[:,3]).shape[0] + 1))
dict_sub_grade = dict(zip(keys, value))

In [62]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [63]:
#now let's replace these values with sub-grade
for i in loan_data_strings[:,3]:
    loan_data_strings[:,3] = np.where(loan_data_strings[:,3] == i,
                                      dict_sub_grade[i],
                                      loan_data_strings[:,3])

KeyError: '5'