##### ndarrays: Originated from the NumPy package and it is a special datatype in Python which can store multiple numeric values in a sequence, elementwise

In [1]:
import numpy as np

### Ndarrays

In [2]:
array_a = np.array([1,2,3])

In [3]:
array_a

array([1, 2, 3])

In [4]:
print(array_a)
#here the data type which is array is not shown

[1 2 3]


In [5]:
type(array_a)

numpy.ndarray

In [6]:
array_a.shape
#the out put shows that it's a vector of length 3

(3,)

In [8]:
array_b = np.array([[7,8,9],[10,11,12]])

In [9]:
type(array_b)

numpy.ndarray

In [10]:
print(array_b)
#it resembles a table which has 2 rows and 3 columns
# dimension = 2*3

[[ 7  8  9]
 [10 11 12]]


In [11]:
array_b.shape

(2, 3)

In [12]:
#if I just wqant to know number of rows
array_b.shape[0]

2

In [13]:
#if I just wqant to know number of columns
array_b.shape[1]

3

In [14]:
array_C = np.array(13)
#This is a scalar
#Not a conventional array

In [15]:
type(array_C)

numpy.ndarray

In [16]:
print(array_C)

13


In [17]:
array_C.shape

()

In [18]:
#but
array_d = np.array([15])
#this is usually done to make the input ready for a perticular function
#coz some functions take input of certain dimension
#this represents like a point on the line

In [19]:
array_d.shape

(1,)

In [20]:
type(array_d)

numpy.ndarray

###### The no. of brackets an array has indicates how many dimensions it requires

### List vs Array

In [21]:
list_a = [[1,2,3],[4,5,6]]

In [22]:
len(list_a)

2

In [23]:
array_a = np.array(list_a)

In [24]:
type(list_a)

list

In [25]:
type(array_a)

numpy.ndarray

So, even though the input is same Python treats list and arrays in different ways which is something we actually want.

In [26]:
print(list_a)

[[1, 2, 3], [4, 5, 6]]


In [27]:
print(array_a)

[[1 2 3]
 [4 5 6]]


In [28]:
array_a.shape

(2, 3)

In [30]:
#list_a.shape
#this code will show error cause, list and array are stored differently

In [31]:
len(list_a)

2

In [32]:
len(list_a[0])
# this means that inner first list has 3 elements

3

In [33]:
list_a

[[1, 2, 3], [4, 5, 6]]

In [34]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
#Now
list_b = list_a[0] + list_a[1]
array_b = array_a[0] + array_a[1]

In [36]:
list_b

[1, 2, 3, 4, 5, 6]

In [37]:
array_b

array([5, 7, 9])

In [39]:
import math
#array_e = math.sqrt(list_a[1,0])
#print(array_e)
#this code will show error as the input is a list

In [40]:
import math
array_e = math.sqrt(array_a[1,0])
print(array_e)


2.0


In [41]:
np.sqrt(array_a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

### String vs Object vs Numbers

In [43]:
lending_co_lt = np.genfromtxt("lending-co-LT.csv", delimiter=',')

In [44]:
lending_co_lt

array([[      nan,       nan,       nan, ...,       nan,       nan,
              nan],
       [1.000e+00,       nan,       nan, ...,       nan,       nan,
        1.660e+04],
       [2.000e+00,       nan,       nan, ...,       nan,       nan,
        1.660e+04],
       ...,
       [1.041e+03,       nan,       nan, ...,       nan,       nan,
        1.660e+04],
       [1.042e+03,       nan,       nan, ...,       nan,       nan,
        1.560e+04],
       [1.043e+03,       nan,       nan, ...,       nan,       nan,
        1.660e+04]])

In [45]:
# another wqay of displaying this is
print(lending_co_lt)
#As you can see the numbers are shown in ye+x format which means y*10^(x)

[[      nan       nan       nan ...       nan       nan       nan]
 [1.000e+00       nan       nan ...       nan       nan 1.660e+04]
 [2.000e+00       nan       nan ...       nan       nan 1.660e+04]
 ...
 [1.041e+03       nan       nan ...       nan       nan 1.660e+04]
 [1.042e+03       nan       nan ...       nan       nan 1.560e+04]
 [1.043e+03       nan       nan ...       nan       nan 1.660e+04]]


In [46]:
lending_co_lt = np.genfromtxt("lending-co-LT.csv", 
                              delimiter=',',
                             dtype = np.int32)
lending_co_lt
#Now the missing values are generated differently

array([[   -1,    -1,    -1, ...,    -1,    -1,    -1],
       [    1,    -1,    -1, ...,    -1,    -1, 16600],
       [    2,    -1,    -1, ...,    -1,    -1, 16600],
       ...,
       [ 1041,    -1,    -1, ...,    -1,    -1, 16600],
       [ 1042,    -1,    -1, ...,    -1,    -1, 15600],
       [ 1043,    -1,    -1, ...,    -1,    -1, 16600]])

In [47]:
lending_co_lt[0,0] + lending_co_lt[0,1]

-2

In [48]:
lending_co_lt = np.genfromtxt("lending-co-LT.csv", 
                              delimiter=',',
                             dtype = np.str_)
lending_co_lt
#Here the values are the symbols stored in those areas
#that means are numbers are not values but just symbols
#so they can't be added
#The different elements within the array can still be stored, cut and formatted

array([['LoanID', 'StringID', 'Product', ..., 'Location', 'Region',
        'TotalPrice'],
       ['1', 'id_1', 'Product B', ..., 'Location 2', 'Region 2',
        '16600.0'],
       ['2', 'id_2', 'Product B', ..., 'Location 3', '', '16600.0'],
       ...,
       ['1041', 'id_1041', 'Product B', ..., 'Location 23', 'Region 4',
        '16600.0'],
       ['1042', 'id_1042', 'Product C', ..., 'Location 52', 'Region 6',
        '15600.0'],
       ['1043', 'id_1043', 'Product B', ..., 'Location 142', 'Region 6',
        '16600.0']], dtype='<U14')

In [49]:
lending_co_lt = np.genfromtxt("lending-co-LT.csv", 
                              delimiter=',',
                             dtype = object)
lending_co_lt
#The data inside is not just plain text we can't freely manipulate
#Object dtype is used for better compatibility with older versions of pandas

array([[b'LoanID', b'StringID', b'Product', ..., b'Location', b'Region',
        b'TotalPrice'],
       [b'1', b'id_1', b'Product B', ..., b'Location 2', b'Region 2',
        b'16600.0'],
       [b'2', b'id_2', b'Product B', ..., b'Location 3', b'', b'16600.0'],
       ...,
       [b'1041', b'id_1041', b'Product B', ..., b'Location 23',
        b'Region 4', b'16600.0'],
       [b'1042', b'id_1042', b'Product C', ..., b'Location 52',
        b'Region 6', b'15600.0'],
       [b'1043', b'id_1043', b'Product B', ..., b'Location 142',
        b'Region 6', b'16600.0']], dtype=object)

In [50]:
lending_co_lt = np.genfromtxt("lending-co-LT.csv", 
                              delimiter=',',
                             dtype = (np.int32, np.str_, np.str_, np.str_, np.str_, np.str_, np.int32))
lending_co_lt
#Output is not very pleasing
#The reason behind it is Arrays usually consist of a single numeric dtype
#We should avoid specifying various dtypes when working with NumPy

array([(  -1, '', '', '', '', '',    -1),
       (   1, '', '', '', '', '', 16600),
       (   2, '', '', '', '', '', 16600), ...,
       (1041, '', '', '', '', '', 16600),
       (1042, '', '', '', '', '', 15600),
       (1043, '', '', '', '', '', 16600)],
      dtype=[('f0', '<i4'), ('f1', '<U'), ('f2', '<U'), ('f3', '<U'), ('f4', '<U'), ('f5', '<U'), ('f6', '<i4')])