In [1]:
import numpy as np

In [2]:
np.__version__

'1.25.0'

In [3]:
np.array([1,2,3]) #1d array

array([1, 2, 3])

In [4]:
twoD = np.array([[1,2,3],[4,5,6]]) #2D array

In [5]:
twoD.shape

(2, 3)

In [6]:
twoD

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
#3D array
threeD = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [8]:
threeD.shape

(1, 3, 3)

In [9]:
threeD

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [ ]:
np.mean()