In [1]:
import numpy as np
#import numpy

In [2]:
s = np.array([5])
s
#A scalar

array([5])

In [3]:
s.shape

(1,)

In [4]:
v = np.array([1,2,3,4,5])
v
# A Vector

array([1, 2, 3, 4, 5])

In [5]:
v.shape

(5,)

In [6]:
#this is how you reshape a vector
v.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [7]:
m = np.array([[1,2,3,4],[5,6,7,8]])
m
# A metrics

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

###### Addititon

In [8]:
m1 = np.array([[7,8,9],[4,5,6]])
m2 = np.array([[1,8,5],[4,4,6]])
m1 + m2

array([[ 8, 16, 14],
       [ 8,  9, 12]])

Arrays should have same dimensions when performing addition or substraction.

###### Multiplication

In [10]:
#np.dot(m1,m2)
#the code won't work
#The rule of multiplication is m * n x n * k

###### Create 2 matrics which will multiply 

###### Transpose
Converting rows into col or vise versa

In [11]:
m1.T

array([[7, 4],
       [8, 5],
       [9, 6]])