In [1]:
import numpy as np

In [2]:
np.__version__

'1.25.1'

In [3]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
m.shape

(2, 3)

In [5]:
m.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
m.T

array([[1, 4],
       [2, 5],
       [3, 6]])