# NumPy Fundamentals

In [1]:
import numpy as np

In [2]:
np.__version__

'1.24.3'

### Indexing

In [3]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

### Specific Values

In [4]:
array_a[1]

array([4, 5, 6])

In [5]:
array_a[0][2]

3

In [6]:
# A better way of doing the above operation is
array_a[1,1]

5

###### Both the operations can be done what's important is to be consistent with one type of code through out the program.

In [7]:
array_a[:,0]
#this tells us that we need the column

array([1, 4])

### Negative Indices

In [8]:
array_b = np.array([1,2,3])
array_b[-1]

3

In [9]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
array_a[-1]

array([4, 5, 6])

In [11]:
array_a[:,-1]

array([3, 6])

### Assigning Values

In [12]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
array_a[0,2] = 9
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [14]:
array_a[0] = 9
array_a

array([[9, 9, 9],
       [4, 5, 6]])

In [15]:
array_a[:,0] = 9
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [16]:
# If we want to change multiple elements we use list
list_a = [7,8,9]
array_a[0] = list_a
array_a

array([[7, 8, 9],
       [9, 5, 6]])

In [17]:
type(array_a[0])
# This shows that once the array has accepted a value in it it's type becomes
# eqyal to array

numpy.ndarray

In [18]:
array_a[:] = 9

In [19]:
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [20]:
array_a = 9
array_a

9

In [21]:
type(array_a)

int

This shows that the 2D array is no more in existence 

In [22]:
array_a = np.array([[1,2,3],[4,5,6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

### Elementwise Properties

Elementwise means that whatever mathmatical computation we are conducting, we are doing it to each element of the array

In [23]:
array_a = np.array([7,8,9])
array_a

array([7, 8, 9])

In [24]:
array_b = np.array([[1,2,3],[4,5,6]])
array_b                    

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
array_a +  2

array([ 9, 10, 11])

In [26]:
array_b + 2

array([[3, 4, 5],
       [6, 7, 8]])

In [27]:
array_a + array_b[0]
# Each individual element is added up with its corresponding counterpart from the other array

array([ 8, 10, 12])

In [28]:
array_a + array_b
#This is posible only if the length of the arrays is equal

array([[ 8, 10, 12],
       [11, 13, 15]])

In [29]:
array_a * array_b

array([[ 7, 16, 27],
       [28, 40, 54]])

Always remember that while Addition and Subtraction the sequence is important

### Types of Data Supported by NumPy

In [33]:
arra_a = np.array([[1,2,3],[4,5,6]])
arra_a

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arra_a = np.array([[1,2,3],[4,5,6]], dtype = "float32")
arra_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [35]:
# Another way of writing this is... 
arra_a = np.array([[1,2,3],[4,5,6]], dtype = np.float32)
arra_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [36]:
arra_a = np.array([[1,2,3],[4,5,6]], np.complex64)
arra_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [44]:
arra_a = np.array([[1,2,3],[4,5,6]], str)
arra_a
#here U1 tells us that the string has a unicode value of lenght up to 1

array([['1', '2', '3'],
       ['4', '5', '6']], dtype='<U1')

In [43]:
arra_a = np.array([[1,2,3],[4,5,6]], bool)
arra_a

array([[ True,  True,  True],
       [ True,  True,  True]])

### Broadcasting

We want to conduct elementwise operations but have elements of different sizes, and/or demision, So we broadcast the smaller variable and create a broadcasted version with the size of the larger one

"Stretching" one variable over the other to produce an output with the same shape.

In [45]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

In [46]:
array_b = np.array([[1],[2]])
array_b

array([[1],
       [2]])

In [47]:
array_c = np.array([[1,2,3],[4,5,6]])
array_c

array([[1, 2, 3],
       [4, 5, 6]])

## Characteristics of NumPy Functions

### Universal Functions
Universal Functions work with NDarrays on an element-by-element bases, an extension of the elementwise operation

https://numpy.org/devdocs/reference/ufuncs.html

In [48]:
np.add(array_a, array_c)

array([[2, 4, 6],
       [5, 7, 9]])

In [49]:
np.add(array_b, array_c)

array([[2, 3, 4],
       [6, 7, 8]])

###### Broadcasting Rules:
1.) The arrays have the same shape

2.) The arrays have the same number of dimension, and the lenght of each dimension is either common or 1

3.) The arrays that have too few dimensions can have their shapees altered with dimension 1, to satisfy the second rule

## Type Casting

Taking every element of an array and changing it to a specified datatype

In [50]:
np.add(array_b, array_c, dtype = np.float64)

array([[2., 3., 4.],
       [6., 7., 8.]])

In [52]:
#np.add(array_b, array_c, dtype = str)
# this will show an error cause the method .add first converts all numbers to str
# And then tries to add it which is not possible in this case.

### Running over an Axis

Running a function along a given axis: 

1.) NumPy breaks down an ND-array into smaller arrays of N-1 many dimension

2.) Applies the function to each one and we can use this feature to run fuction along each row or column

In [53]:
np.mean(array_c, axis = 0)

array([2.5, 3.5, 4.5])

In [54]:
array_c

array([[1, 2, 3],
       [4, 5, 6]])